<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kvitoslava Yarish">
<meta name="dcterms.date" content="2024-12-01">

<title>Calculation and graphic work in Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="final_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_files/libs/quarto-html/quarto.js"></script>
<script src="final_files/libs/quarto-html/popper.min.js"></script>
<script src="final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_files/libs/quarto-html/quarto-syntax-highlighting-07ba0ad10f5680c660e360ac31d2f3b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_files/libs/bootstrap/bootstrap-e83ba85e45e776bbf01e685f7d79a4fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Calculation and graphic work in Statistics</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kvitoslava Yarish </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-sample-data" class="level2">
<h2 class="anchored" data-anchor-id="the-sample-data">The sample data</h2>
<div id="3eec6db7" class="cell" data-message="false" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>[0.63, 0.74, 2.44, 0.27, 2.46, 2.41, 0.77, 4.78, 1.58, 0.15, 0.02, 1.67, 1.93, 0.37, 0.82, 0.05, 2.34, 0.19, 3.23, 1.62, 2.41, 0.18, 0.1, 0.75, 1.97, 2.4, 0.06, 4.81, 0.87, 2.05, 0.32, 0.46, 1.47, 0.08, 0.23, 3.94, 0.57, 0.32, 1.89, 2.45, 0.27, 2.51, 0.17, 0.04, 0.57, 2.44, 1.05, 5.69, 0.47, 0.59, 0.64, 2.09, 1.61, 0.29, 0.82, 1.82, 0.03, 0.78, 0.36, 0.52, 0.09, 1.59, 0.46, 1.17, 0.74, 0.11, 1.51, 2.33, 0.58, 0.11, 1.97, 0.06, 0.35, 0.25, 0.61, 0.22, 0.79, 1.59, 3.54, 0.62, 0.67, 1.57, 0.47, 0.3, 0.05, 2.09, 0.23, 1.91, 1.5, 0.35, 1.48, 2.75, 1.43, 2.54, 1.45, 1.38, 0.23, 0.81, 1.19, 1.39]</code></pre>
</div>
</div>
<p>Based form the sample provided it can be concluded that this is continuous distribution as numbers are decimal mostly and almost do not have dublicates</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Size of sample</th>
<th>Min element</th>
<th>Max element</th>
<th>Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>100</td>
<td>0.02</td>
<td>5.69</td>
<td>5.670000000000001</td>
</tr>
</tbody>
</table>
<section id="interval-frequency-distribution" class="level3">
<h3 class="anchored" data-anchor-id="interval-frequency-distribution">Interval frequency distribution</h3>
<p>To build interval frequency distribution I will divide sample into classes based on Sturge’s rule using this formula <span class="math display">\[
m = 1 + \left\lfloor \log_2 n \right\rfloor
\]</span></p>
<p>Where: - ( m ) is the number of classes. - ( n ) is the size of the sample.</p>
<p>To determine the length of class I will use this formula <span class="math display">\[
h = \frac{x_{(n)} - x_{(1)}}{m}.
\]</span></p>
<p>Also the middle of each class will be calculated by <span class="math display">\[
x_k^*=\frac{y_{k-1}+y_k}{2}.
\]</span></p>
<hr>
<p>Amount of classes is 7.0 and the width of classes is 0.81</p>
<p>Formulas used to calculate metrics in a table below</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Class</th>
<th style="text-align: center;">Middle of the class</th>
<th style="text-align: center;">Frequency</th>
<th style="text-align: center;">Cumulative frequency</th>
<th style="text-align: center;">Relative frequency</th>
<th style="text-align: center;">Cumulative relative frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\Delta_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_1^*\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_1^*\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\nu_1=\frac{n_1}{n}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\nu_1^*=\nu_1\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\Delta_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_2^*\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_2^*=n_1+n_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\nu_2=\frac{n_2}{n}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\nu_2^*=\nu_1+\nu_2\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\Delta_m\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_m^*\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_m\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_m^*\!=n_1\!+\!\ldots\!+\!n_m\!=\!n\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\nu_m=\frac{n_m}{n}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\nu_m^*=\nu_1+\ldots+\nu_m=1\)</span></td>
</tr>
</tbody>
</table>
<div id="b61624dc" class="cell" data-message="false" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Bins</th>
<th data-quarto-table-cell-role="th">Bin_Middle</th>
<th data-quarto-table-cell-role="th">Frequency</th>
<th data-quarto-table-cell-role="th">Cumulative_Frequency</th>
<th data-quarto-table-cell-role="th">Relative_Frequency</th>
<th data-quarto-table-cell-role="th">Cumulative Relative Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0 - 0.81</td>
<td>0.40</td>
<td>51</td>
<td>51</td>
<td>0.51</td>
<td>0.51</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.81 - 1.62</td>
<td>1.22</td>
<td>20</td>
<td>71</td>
<td>0.20</td>
<td>0.71</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.62 - 2.43</td>
<td>2.03</td>
<td>16</td>
<td>87</td>
<td>0.16</td>
<td>0.87</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.43 - 3.24</td>
<td>2.84</td>
<td>8</td>
<td>95</td>
<td>0.08</td>
<td>0.95</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3.24 - 4.05</td>
<td>3.64</td>
<td>2</td>
<td>97</td>
<td>0.02</td>
<td>0.97</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>4.05 - 4.86</td>
<td>4.46</td>
<td>2</td>
<td>99</td>
<td>0.02</td>
<td>0.99</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>4.86 - 5.77</td>
<td>5.32</td>
<td>1</td>
<td>100</td>
<td>0.01</td>
<td>1.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><br> So that sum of all areas of obtained rectangles equals to 1 I will use the corrected relative frequencies. <span class="math display">\[
h_k=\frac{\nu_k}{l(\Delta_k)}, \quad k=1, \ldots, m,
\]</span></p>
<div id="c50c657d" class="cell" data-fig-asp="0.618" data-fig-width="10" data-message="false" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-6-output-1.png" width="815" height="546" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="empirical-cumulative-distribution-function" class="level3">
<h3 class="anchored" data-anchor-id="empirical-cumulative-distribution-function">Empirical cumulative distribution function</h3>
<p>The formula used to calculate the empirical cumulative distribution function <span class="math display">\[
\begin{aligned}
F_n^*(x) &amp;= \frac{\text{number of } x_k \text{ that are less or equal to the right end of a class that contains } x}{n}, \\
&amp;= \begin{cases}
0, &amp; x &lt; y_0, \\
\frac{n_1}{n}, &amp; y_0 \leq x &lt; y_1, \\
\frac{n_1 + n_2}{n}, &amp; y_1 \leq x &lt; y_2, \\
\vdots, &amp; \vdots \\
\frac{n_1 + \ldots + n_{m-1}}{n}, &amp; y_{m-2} \leq x &lt; y_{m-1}, \\
1, &amp; x \geq y_{m-1}.
\end{cases} \\
&amp;= \begin{cases}
0, &amp; x &lt; y_0, \\
\nu_1^*, &amp; y_0 \leq x &lt; y_1, \\
\nu_2^*, &amp; y_1 \leq x &lt; y_2, \\
\vdots, &amp; \vdots \\
\nu_{m-1}^*, &amp; y_{m-2} \leq x &lt; y_{m-1}, \\
1, &amp; x \geq y_{m-1}.
\end{cases}
\end{aligned}
\]</span></p>
<p>For our realization the empirical cumulative distribution function has a form</p>
<div id="8c4c8bd6" class="cell" data-message="false" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>[0.51, 0.71, 0.87, 0.95, 0.97, 0.99, 1.0]
[0.0, 0.81, 1.62, 2.43, 3.24, 4.05, 4.86, 5.77]</code></pre>
</div>
</div>
<p><span class="math display">\[
F_n^*(x)=\left\{\begin{array}{ll}
0, &amp; x &lt; 0.0, \\
0.95, &amp;0.0 \leq x &lt; 0.81, \\
0.71, &amp; 0.81 \leq x &lt; 1.62, \\
0.87, &amp; 1.62 \leq x &lt; 2.43, \\
0.95, &amp; 2.43 \leq x &lt; 3.24, \\
0.97, &amp; 3.24 \leq x &lt; 4.05, \\
0.99, &amp;4.05\leq x &lt; 4.86, \\
1, &amp; x \geq 4.86.
\end{array}\right.
\]</span></p>
<div id="3ddc7f0a" class="cell" data-fig-asp="0.618" data-fig-width="10" data-message="false" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-8-output-1.png" width="825" height="515" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sample-characteristics-of-a-population" class="level2">
<h2 class="anchored" data-anchor-id="sample-characteristics-of-a-population">Sample characteristics of a population</h2>
<p>In this part I will calculate characteristics both grouped and general.</p>
<blockquote class="blockquote">
<p>Sample mean is defined as</p>
<p><span class="math display">\[
\overline{x}=\frac{1}{n}\sum\limits_{i=1}^nx_i.
\]</span></p>
<p>In case of a grouped data the following formula is used</p>
<p><span class="math display">\[
\overline{x}=\frac{1}{n}\sum\limits_{i=1}^mn_ix^*_i=\sum\limits_{i=1}^m\nu_ix^*_i.
\]</span></p>
</blockquote>
<blockquote class="blockquote">
<p>Let <span class="math inline">\(x_{(1)}\leq x_{(2)}\leq \ldots\leq x_{(n)}\)</span> be a variation series. <em>Sample median</em> is defined as</p>
<p><span class="math display">\[
\mbox{Me}^*X=\left\{
\begin{array}{ll}
x_{(k+1)}, &amp; n=2k+1, \\
\dfrac{x_{(k)}+x_{(k+1)}}{2}, &amp; n=2k.
\end{array}
\right.
\]</span></p>
<p>For grouped data <span class="math display">\[
n^*_{me-1}&lt;\frac{n}{2}, \quad n^*_{me}\geq\frac{n}{2},
\]</span></p>
<p>where <span class="math inline">\(n^*_k\)</span> is a cumulative frequency of <span class="math inline">\(k\)</span>-th class; - an element of the obtained class, that corresponds to the median, is found by the formula</p>
<p><span class="math display">\[
\mbox{Me}^*X=y_{me-1}+h\cdot\frac{\frac{n}{2}-n^*_{me-1}}{n_{me}},
\]</span></p>
<p>where <span class="math inline">\(h\)</span> is a width of a class, <span class="math inline">\(y_{me-1}\)</span> and <span class="math inline">\(n_{me}\)</span> are left bound and frequency of a class that contains the median.</p>
</blockquote>
<blockquote class="blockquote">
<p>The value of the mode is found by the formula</p>
<p><span class="math display">\[
\mbox{Mo}^*X=y_{mo-1}+h\cdot\frac{n_{mo}-n_{mo-1}}{(n_{mo}-n_{mo-1})+(n_{mo}-n_{mo+1})}
\]</span></p>
<p>where <span class="math inline">\(h\)</span> is a width of a class, <span class="math inline">\(y_{mo-1}\)</span> is the left bound of the modal class, <span class="math inline">\(n_{mo}\)</span>, <span class="math inline">\(n_{mo-1}\)</span>, <span class="math inline">\(n_{mo+1}\)</span> are frequencies of modal, pre-modal and post-modal classes.</p>
</blockquote>
<table class="caption-top table">
<caption>Measures of central tendency</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Sample mean</th>
<th>Sample mean (grouped)</th>
<th>Sample median</th>
<th>Sample median (grouped)</th>
<th>Sample mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.21</td>
<td>1.215</td>
<td>0.785</td>
<td>0.794</td>
<td>0.504</td>
</tr>
</tbody>
</table>
<p>As mean, median and mode are not the same or close to each other, the sample provided does not follow normal distribution.</p>
<section id="measures-of-dispersion" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-dispersion">Measures of dispersion</h3>
<blockquote class="blockquote">
<p>Let the expected value of the population be known, <span class="math inline">\(\mathbb{E}X=\mu\)</span>. Then the sample variance is determined as follows</p>
<p><span class="math display">\[
\mbox{Var}^*X=\frac{1}{n}\sum\limits_{i=1}^n(x_i-\mu)^2.
\]</span></p>
<p>In case of a grouped data the following formula is used</p>
<p><span class="math display">\[
\mbox{Var}^*X=\frac{1}{n}\sum\limits_{i=1}^mn_i\left(x^*_i-\mu\right)^2=\sum\limits_{i=1}^m\nu_i\left(x^*_i-\mu\right)^2.
\]</span></p>
</blockquote>
<blockquote class="blockquote">
<p>If the expected value of the population is unknown, then it is considered the sample variance</p>
<p><span class="math display">\[
\mbox{Var}^{**}X=\frac{1}{n}\sum\limits_{i=1}^n\left(x_i-\overline{x}\right)^2
\]</span></p>
<p>or <em>corrected (unbiased)</em> sample variance</p>
<p><span class="math display">\[
\mbox{Var}^{***}X=\frac{1}{n-1}\sum\limits_{i=1}^n\left(x_i-\overline{x}\right)^2.
\]</span></p>
<p>Corresponding formulae for grouped data are of the form</p>
<p><span class="math display">\[
\mbox{Var}^{**}X=\frac{1}{n}\sum\limits_{i=1}^mn_i\left(x^*_i-\overline{x}\right)^2=\sum\limits_{i=1}^m\nu_i\left(x^*_i-\overline{x}\right)^2 \quad \mbox{та} \quad
\mbox{Var}^{***}X=\frac{1}{n-1}\sum\limits_{i=1}^mn_i\left(x^*_i-\overline{x}\right)^2=
\frac{n}{n-1}\sum\limits_{i=1}^m\nu_i\left(x^*_i-\overline{x}\right)^2.
\]</span></p>
</blockquote>
<p>It is defined also a <em>sample standard deviation</em> - the square root of the sample variance <span class="math display">\[
\sigma^*_X=\sqrt{\mbox{Var}^*X}, \quad \sigma^{**}_X =\sqrt{\mbox{Var}^{**}X}, \quad \sigma^{***}_X=\sqrt{\mbox{Var}^{***}X}.
\]</span></p>
<table class="caption-top table">
<caption>Measures of dispersion</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Sample variance</th>
<th>Corrected sample variance</th>
<th>Sample variance (grouped)</th>
<th>Corrected sample variance (grouped)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.288</td>
<td>1.301</td>
<td>1.153</td>
<td>1.165</td>
</tr>
</tbody>
</table>
</section>
<section id="measures-of-a-shape" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-a-shape">Measures of a shape</h3>
<blockquote class="blockquote">
<p>let’s consider a <em>sample moment</em> of <span class="math inline">\(k\)</span>-th order</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math display">\[
\mu^*_k=\frac{1}{n}\sum\limits_{i=1}^nx_i^k
\]</span></p>
</blockquote>
<blockquote class="blockquote">
<p>and a <em>sample central moment</em> of <span class="math inline">\(k\)</span>-th order</p>
</blockquote>
<blockquote class="blockquote">
<p><span class="math display">\[
\mu^*_{k, 0}=\frac{1}{n}\sum\limits_{i=1}^n\left(x_i-\overline{x}\right)^k.
\]</span></p>
</blockquote>
<blockquote class="blockquote">
<p>In particular, <span class="math inline">\(\mu^*_1=\overline{x}\)</span>, <span class="math inline">\(\mu^*_{2, 0}=\mbox{Var}^{**}X\)</span>.</p>
</blockquote>
<blockquote class="blockquote">
<p><em>Sample skewness</em> is defined as</p>
<p><span class="math display">\[
\mbox{Sk}^*X=\frac{\mu^*_{3, 0}}{\left(\sigma^{***}_X\right)^3}
\]</span></p>
<p>and it characterizes the degree of symmetry of the distribution of data with respect to the sample mean: - <span class="math inline">\(\mbox{Sk}^*X\approx0\)</span> - the data are symmetric with respect to the sample mean; - <span class="math inline">\(\mbox{Sk}^*X&gt;0\)</span> - the data have right-sided asymmetry (long right tail); - <span class="math inline">\(\mbox{Sk}^*X&lt;0\)</span> - the data have left-sided asymmetry (long left tail).</p>
</blockquote>
<table class="caption-top table">
<caption>Measures of a shape</caption>
<thead>
<tr class="header">
<th>Sample skeweness</th>
<th>Sample kurtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.454</td>
<td>2.466</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="making-a-hypothesis-about-the-distribution-of-a-population" class="level2">
<h2 class="anchored" data-anchor-id="making-a-hypothesis-about-the-distribution-of-a-population">Making a hypothesis about the distribution of a population</h2>
<div id="5b030067" class="cell" data-fig-asp="0.618" data-fig-width="10" data-message="false" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="final_files/figure-html/cell-10-output-1.png" width="1420" height="465" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Because we have positive skew, data is definitely not uniform distribution. Also, the pdf of our distribution is left skewed. So I assume that the most suitable distribution is exponential.</p>
</section>
<section id="point-estimation" class="level2">
<h2 class="anchored" data-anchor-id="point-estimation">Point estimation</h2>
<p>Let <span class="math inline">\(x_1, \ldots, x_n\)</span> is a realization of a sample <span class="math inline">\(X_1, \ldots, X_n\)</span> of a population. On the previous step we assumed that the population has the exponential distribution <span class="math inline">\(X\simeq\mbox{Exp}(\frac{1}{\lambda})\)</span> with unknown parameter <span class="math inline">\(\vec{\theta} = (\lambda)\)</span>.</p>
<section id="method-of-moments" class="level3">
<h3 class="anchored" data-anchor-id="method-of-moments">Method of Moments</h3>
<p>Let’s estimate the value of unknown parameter with the help of <em>method of moments</em>. For this we equalize an expected value <span class="math inline">\(\mathbb{E}X = \mu\)</span> with a sample mean <span class="math inline">\(\overline{X}\)</span></p>
<p><span class="math display">\[
\begin{aligned}
\frac{1}{\lambda} &amp;= t, \\
f_Y(y; t) &amp;= t e^{-t y}, \quad y \geq 0, \\
\mathbb{E}[Y] &amp;= \int_{0}^{\infty} y t e^{-t y} \, dy, \\
&amp;= t \int_{0}^{\infty} y e^{-t y} \, dy, \\
&amp;= \left[ -\frac{y e^{-t y}}{t} \right]_{0}^{\infty} + \int_{0}^{\infty} \frac{e^{-t y}}{t} \, dy, \\
&amp;= \left( 0 - \left(-\frac{1}{t^2}\right) \right), \\
\mathbb{E}[Y] &amp;= \frac{1}{t}, \\
\frac{1}{t} &amp;= \overline{X}, \\
t &amp;= \frac{1}{\overline{X}}, \\
\lambda^* &amp;= \overline{X}, \\
\theta^* &amp;= \overline{X}.
\end{aligned}
\]</span></p>
<p>So, for the given realization we have that</p>
<p><span class="math display">\[ \theta^* = 1.21 \]</span></p>
</section>
<section id="maximum-likelihood-estimation" class="level3">
<h3 class="anchored" data-anchor-id="maximum-likelihood-estimation">Maximum likelihood estimation</h3>
$$
<span class="math display">\[\begin{aligned}
\frac{1}{\lambda} &amp;= t, \\
\frac{d}{dt} L(t \mid x_1, x_2, \ldots, x_n)
&amp;= \frac{d}{dt} t^n \left[ e^{-t(x_1 + x_2 + \ldots + x_n)} \right] \\
&amp;= \frac{d}{dt} \log \left( t^n \left[ e^{-t(x_1 + x_2 + \ldots + x_n)} \right] \right) \\
&amp;= \frac{d}{dt} \log(t^n) + \log \left[ e^{-t(x_1 + x_2 + \ldots + x_n)} \right] \\
&amp;= \frac{d}{dt} \left[ n \log(t) \right] - \frac{d}{dt} \left[ \t(x_1 + x_2 + \ldots + x_n) \right] \\
&amp;= \frac{n}{t} - (x_1 + x_2 + \ldots + x_n)\\

\text{Setting the derivative to zero:} \\
0 &amp;= n \frac{1}{t} - (x_1 + x_2 + \ldots + x_n) \\
(x_1 + x_2 + \ldots + x_n) &amp;= n \frac{1}{t} \\
t (x_1 + x_2 + \ldots + x_n) &amp;= n \\
t &amp;= \frac{n}{x_1 + x_2 + \ldots + x_n}\\
t = \frac{1}{\overline{X}}\\
\theta^* &amp;= \overline{X}.
\end{aligned}\]</span>
<p>$$</p>
<p>So <span class="math inline">\(\lambda^*\)</span> is equal to</p>
<div id="81c51ee0" class="cell" data-message="false" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>1.21</code></pre>
</div>
</div>
</section>
</section>
<section id="properties-of-point-estimators" class="level2">
<h2 class="anchored" data-anchor-id="properties-of-point-estimators">Properties of point estimators</h2>
<p>n both methods, I obtained similar point estimators. In this section, I will focus on evaluating their statistical properties to determine their quality as estimators, rather than comparing the methods directly. Specifically, I will assess whether the estimators exhibit desirable properties such as unbiasedness, consistency, and efficiency.</p>
<section id="consistency" class="level3">
<h3 class="anchored" data-anchor-id="consistency">Consistency</h3>
<p><span class="math display">\[
\begin{aligned}
\text{From the LLN, we can say that if :} \theta &amp;= \mathbb{E}[X]
\text{Then, } \theta^* &amp;= \overline{X}, \\
\text{is a consistent estimator of } \theta.
\end{aligned}
\]</span> ### Unbiasedness <span class="math display">\[
\begin{aligned}
\theta &amp;= \lambda\\
\theta^* &amp;= \overline{X}\\
E[\bar{X}] &amp;= \frac{1}{n} \sum_{i=1}^{n} E[X_i]\\
&amp;= \frac{1}{n} {n} \lambda\\
&amp;= \lambda
\end{aligned}
\]</span> <span class="math display">\[
E[\theta^*_n] = \theta, \, \forall \theta \in \Theta, \quad \text{this means that the estimator is unbiased.}
\]</span></p>
</section>
<section id="efficiency" class="level3">
<h3 class="anchored" data-anchor-id="efficiency">Efficiency</h3>
<p>For <span class="math inline">\(X_i \sim \text{Exp}\left(\frac{1}{\theta}\right)\)</span>, the variance of <span class="math inline">\(X_i\)</span> is: <span class="math display">\[
\mathrm{Var}(X_i) = \theta^2.
\]</span></p>
<p>The variance of the sample mean <span class="math inline">\(\bar{X}\)</span> is: <span class="math display">\[
\mathrm{Var}(\bar{X}) = \frac{\mathrm{Var}(X_i)}{n} = \frac{\theta^2}{n}.
\]</span></p>
<p>The Fisher Information for <span class="math inline">\(n\)</span> observations is: <span class="math display">\[
\mathcal{I}_n(\theta) = -\mathbb{E}\left[\frac{\partial^2 \ell}{\partial \theta^2}\right] = \frac{n}{\theta^2}.
\]</span></p>
<p>The Cramér-Rao Lower Bound (CRLB) is: <span class="math display">\[
\text{CRLB} = \frac{1}{\mathcal{I}_n(\theta)} = \frac{\theta^2}{n}.
\]</span></p>
<p>The variance of <span class="math inline">\(\bar{X}\)</span> is: <span class="math display">\[
\mathrm{Var}(\bar{X}) = \frac{\theta^2}{n}.
\]</span></p>
<p>Since <span class="math inline">\(\mathrm{Var}(\bar{X}) = \text{CRLB}\)</span>, the estimator <span class="math inline">\(\bar{X}\)</span> achieves the Cramér-Rao Lower Bound, thus is efficient.</p>
<p>The estimator <span class="math inline">\(\bar{X}\)</span> satisfies all the desired properties (unbiasedness, consistency, and efficiency). Therefore, it will be used in the subsequent steps.</p>
</section>
</section>
<section id="confidence-intervals-for-unknown-parameters-of-a-population" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-for-unknown-parameters-of-a-population">Confidence intervals for unknown parameters of a population</h2>
<section id="confidence-interval-for-the-parameter-mu-with-an-unknown-sigma2" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-for-the-parameter-mu-with-an-unknown-sigma2">Confidence interval for the parameter <span class="math inline">\(\mu\)</span> with an unknown <span class="math inline">\(\sigma^2\)</span></h3>
<p>Let’s find confidence intervals for parameters <span class="math inline">\(\mu\)</span> of the given confidence level <span class="math inline">\(\gamma\)</span> = 0.95.</p>
<p><span class="math display">\[
\mu_1 = \overline{X} - \frac{t_{\gamma}\sqrt{\mbox{Var}^{**}X}}{\sqrt{n-1}}, \quad a_2 = \overline{X} + \frac{t_{\gamma}\sqrt{\mbox{Var}^{**}X}}{\sqrt{n-1}}.
\]</span></p>
<p>The value of <span class="math inline">\(t_{\gamma}\)</span> is defined from</p>
<p><span class="math display">\[
\mathbb{P}(|St_{n-1}|&lt;t_{\gamma}) = \gamma,
\]</span></p>
<p>where a random variable <span class="math inline">\(St_{n-1}\)</span> has Student’s distribution with <span class="math inline">\(n-1\)</span> degrees of freedom. For <span class="math inline">\(\gamma=0.95\)</span>, <span class="math inline">\(n=100\)</span> we have <span class="math inline">\(t_{\gamma} = np.float64(1.9842169515086827)\)</span>. Also <span class="math inline">\(\overline{X}\)</span> = 1.21, <span class="math inline">\(Var^{**}X\)</span> = 1.301. Then the confidence interval is of the form</p>
<p>(0.98254, 1.43746)</p>
</section>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis testing</h2>
<p>I have two hypotheses:</p>
<p><span class="math inline">\(H_0\)</span> - the data follows the exponential distribution <span class="math inline">\(X\simeq\mbox{Exp}(\frac{1}{\lambda})\)</span> <span class="math inline">\(\lambda\)</span> = 1.21</p>
<p><span class="math inline">\(H_1\)</span> - this is another distribution (I am cooked)</p>
<p>To verify the hypotheses I will use the use the chi-squared goodness-of-fit test. Now the number of parameters equals <span class="math inline">\(s=1\)</span>. A maximum likelihood estimators have a form</p>
<p><span class="math display">\[
\lambda^*=\overline{X}, \quad \mbox{where} \quad \overline{X}=\frac{1}{n}\sum\limits_{i=1}^nX_i.
\]</span></p>
<p>For a given realization we have that <span class="math inline">\(\mu^*=\)</span> 1.21.</p>
<p>Let’s divide a set of all possible values of random variable <span class="math inline">\(X\)</span> in to classes</p>
<p><span class="math display">\[
\mathbb{R} = \cup_{i=1}^m \hat{\Delta}_i.
\]</span></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 28%">
<col style="width: 11%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Class</th>
<th style="text-align: center;">Frequency</th>
<th style="text-align: center;">Theoretical frequency</th>
<th style="text-align: center;"><span class="math inline">\(O - E\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\frac{(O - E)^2}{E}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\hat{\Delta}_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(np_1\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\hat{\Delta}_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(np_2\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\hat{\Delta}_m\)</span></td>
<td style="text-align: center;"><span class="math inline">\(n_m\)</span></td>
<td style="text-align: center;"><span class="math inline">\(np_m\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<div id="584d0188" class="cell" data-message="false" data-execution_count="12">
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Bins</th>
<th data-quarto-table-cell-role="th">Frequency</th>
<th data-quarto-table-cell-role="th">Theoretical_freq</th>
<th data-quarto-table-cell-role="th">o_e</th>
<th data-quarto-table-cell-role="th">o_e_2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0 - 0.81</td>
<td>51</td>
<td>48.7</td>
<td>2.3</td>
<td>0.108624</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.81 - 1.62</td>
<td>20</td>
<td>25.0</td>
<td>-5.0</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.62 - 2.43</td>
<td>16</td>
<td>12.8</td>
<td>3.2</td>
<td>0.800000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.43 - 3.24</td>
<td>8</td>
<td>6.6</td>
<td>1.4</td>
<td>0.296970</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3.24 - 4.05</td>
<td>2</td>
<td>3.4</td>
<td>-1.4</td>
<td>0.576471</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>4.05 - 4.86</td>
<td>2</td>
<td>1.7</td>
<td>0.3</td>
<td>0.052941</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>4.86 - 5.77</td>
<td>1</td>
<td>1.0</td>
<td>0.0</td>
<td>0.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Because theoretical frequency in bins 4-6 is less then 5. We need to join these classes.</p>
<div id="4f596f79" class="cell" data-message="false" data-execution_count="13">
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Bins</th>
<th data-quarto-table-cell-role="th">Frequency</th>
<th data-quarto-table-cell-role="th">Theoretical_freq</th>
<th data-quarto-table-cell-role="th">o_e</th>
<th data-quarto-table-cell-role="th">o_e_2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0.0 - 0.81</td>
<td>51</td>
<td>48.7</td>
<td>2.3</td>
<td>0.108624</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0.81 - 1.62</td>
<td>20</td>
<td>25.0</td>
<td>-5.0</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1.62 - 2.43</td>
<td>16</td>
<td>12.8</td>
<td>3.2</td>
<td>0.800000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2.43 - 3.24</td>
<td>8</td>
<td>6.6</td>
<td>1.4</td>
<td>0.296970</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3.24-5.77</td>
<td>5</td>
<td>6.1</td>
<td>-1.1</td>
<td>0.198361</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Consider a significance level <span class="math inline">\(\alpha=0.05\)</span>. The number of classes equals <span class="math inline">\(m=5\)</span>, the number of parameters <span class="math inline">\(s=1\)</span>, so the critical value <span class="math inline">\(x_{0.05}\)</span> equals to the quantile of the level <span class="math inline">\(1 - \alpha = 0.95\)</span> of the chi-squared distribution with <span class="math inline">\(m - s - 1= 5 - 1 - 1 = 3\)</span> degrees of freedom</p>
<p>The value of the chi-squared statistic equals <span class="math display">\[
\hat{\chi}^2(75) = 2.39.
\]</span></p>
<p><span class="math display">\[
x_{\alpha} = 7.8147.
\]</span></p>
<p>We have that <span class="math inline">\(\hat{\chi}^2(100) = 2.39 &lt; 7.8147 = x_{0.05}\)</span>, so on the significance level <span class="math inline">\(\alpha=0.05\)</span> we do not have sufficient grounds to reject the <span class="math inline">\(H_0\)</span>. Therefore, the data follows exponential distribution <span class="math inline">\(\mbox{Exp}(\frac{1}{1.25})\)</span>.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>